languaje: python 
python: 
- "3.6"
#command to install dependencies
install: "pip install --user coverage"
"pip install mock==2.0"
#command to run tests
script:
- coverage run test_sumar.py
- coverage report
