language: python 
python: "3.6"
#command to install dependencies
install: 
- "pip install mock==2.0" 
- "pip install coverage"

#command to run tests
script:
- coverage run test_sumar.py
- coverage report
